name: app_architecture

packages:
  - app
  - libraries/**

command:
  bootstrap:
    environment:
      sdk: '>=3.3.3 <4.0.0'
      flutter: ">=1.17.0"

    dependencies:
        cupertino_icons: ^1.0.2
        http: ^1.2.1
        json_annotation: ^4.8.1
        get_it: ^7.7.0
        rxdart: ^0.27.7

    dev_dependencies:
      build_runner: ^2.4.9
      json_serializable: ^6.7.1